services:
  mlflow:
    restart: always
    build:
      context: mlflow
    command: server --app-name basic-auth --host 0.0.0.0 --port 5000
    networks:
      - dokploy-network
    volumes:
      - run_data:/mlruns
      - artifact_data:/mlartifacts
      - auth_data:/auth_data
      - ./mlflow/auth_config.ini:/auth_config.ini
    environment:
      - MLFLOW_FLASK_SERVER_SECRET_KEY=${SECRET_KEY}
      - MLFLOW_AUTH_CONFIG_PATH=/auth_config.ini

networks:
  dokploy-network:
    external: true

volumes:
  run_data:
    driver: local
  artifact_data:
    driver: local
  auth_data:
    driver: local